# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rArDr3_pVhH_oqaRYaTtoS10ik-2W9_r
"""

import json
from datetime import datetime

def load_sample(path) -> list[str]:
    with open(path, 'r') as file:
        return [line.strip() for line in file if line.strip()]

def generate_json(transactions: list) -> dict:
    total = 0
    name = ""
    for transaction in transactions:
        data = transaction.split()
        name = data[0]
        montant = int(data[2].replace("€", ""))
        total += montant

    return {"name": name, "total_sent": total}

def save_result(path: str, result: dict):

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"result_sample_{timestamp}.json"
    filepath = os.path.join(path, filename)

    with open(filepath, 'w') as json_file:
        json.dump(result, json_file, indent=4)

def save_result(path: str, result: list[dict]) -> None:
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{path}/result_sample_{timestamp}.json"

    with open(filename, 'w', encoding='utf-8') as json_file:
        json.dump(result, json_file, ensure_ascii=False, indent=4)

    print(f"Résultat sauvegardé dans : {filename}")